name: 'Read Property'
description: 'Read property from .properties file'
inputs:
  path:
    description: 'The path to properties file to read'
    required: true
  property:
    description: 'The property you want to read'
    required: true
outputs:
  value:
    description: 'The value of the given property'
runs:
  using: 'node12'
  main: 'index.js'